name: ci

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: init node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: init pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: get pnpm store
      id: pnpm-store
      run: echo "PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-store.outputs.PATH }}
        key: pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: pnpm-store-

    - name: install deps
      run: pnpm install --frozen-lockfile --strict-peer-dependencies

    - name: check
      run: pnpm check
      continue-on-error: true

    - name: fmt
      run: pnpm fmt
      continue-on-error: true

    - name: build
      run: pnpm build
      continue-on-error: true

    - name: test
      run: pnpm test
      continue-on-error: true
